[schwab]
client_id = "S3JxXbewWhzuTIwzxxgZpbpsmFsOQXPXNMK1VmmOAygfNA2E"
client_secret = "B316JxUxpclBAwNKDmzno8CsES7jO0QmwJw9hbuiNRZ9cs16IXAhb4FOtmquW9S3"
callback_url = "https://127.0.0.1:8182/"
token_file = "~/.local/share/gex_app/schwab_token.json"
base_url = "https://api.schwabapi.com"
max_token_age_days = 7
[telegram]
enabled = true
BOT_TOKEN = "8866995558:AAGlrp7k2kloCcvYECtRJdL52aMCMwhWJ9c"
CHAT_ID = "1199946861"

